<?php

/**
 * BaseProjectUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $user_id
 * 
 * @method integer     getProjectId()  Returns the current record's "project_id" value
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method ProjectUser setProjectId()  Sets the current record's "project_id" value
 * @method ProjectUser setUserId()     Sets the current record's "user_id" value
 * 
 * @package    timeboxx
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_project_user');
        $this->hasColumn('project_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}