<?php

/**
 * BaseSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $culture
 * @property boolean $reminder
 * @property boolean $locked
 * @property User $User
 * 
 * @method integer getUserId()   Returns the current record's "user_id" value
 * @method string  getCulture()  Returns the current record's "culture" value
 * @method boolean getReminder() Returns the current record's "reminder" value
 * @method boolean getLocked()   Returns the current record's "locked" value
 * @method User    getUser()     Returns the current record's "User" value
 * @method Setting setUserId()   Sets the current record's "user_id" value
 * @method Setting setCulture()  Sets the current record's "culture" value
 * @method Setting setReminder() Sets the current record's "reminder" value
 * @method Setting setLocked()   Sets the current record's "locked" value
 * @method Setting setUser()     Sets the current record's "User" value
 * 
 * @package    timeboxx
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_settings');
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('culture', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('reminder', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('locked', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}