<?php

/**
 * BaseRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $account_id
 * @property timestamp $deleted_at
 * @property Account $Account
 * @property Doctrine_Collection $Credentials
 * @property Doctrine_Collection $ProjectUsers
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getAccountId()    Returns the current record's "account_id" value
 * @method timestamp           getDeletedAt()    Returns the current record's "deleted_at" value
 * @method Account             getAccount()      Returns the current record's "Account" value
 * @method Doctrine_Collection getCredentials()  Returns the current record's "Credentials" collection
 * @method Doctrine_Collection getProjectUsers() Returns the current record's "ProjectUsers" collection
 * @method Role                setName()         Sets the current record's "name" value
 * @method Role                setAccountId()    Sets the current record's "account_id" value
 * @method Role                setDeletedAt()    Sets the current record's "deleted_at" value
 * @method Role                setAccount()      Sets the current record's "Account" value
 * @method Role                setCredentials()  Sets the current record's "Credentials" collection
 * @method Role                setProjectUsers() Sets the current record's "ProjectUsers" collection
 * 
 * * @package    sutimeboxx
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_role');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('account_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('deleted_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id'));

        $this->hasMany('Credential as Credentials', array(
             'refClass' => 'RoleCredential',
             'local' => 'role_id',
             'foreign' => 'credential_id'));

        $this->hasMany('ProjectUser as ProjectUsers', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}