<?php

/**
 * BaseTimeLogItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property double $value
 * @property integer $type_id
 * @property integer $project_id
 * @property integer $user_id
 * @property TimeItemType $TimeItemType
 * @property User $User
 * @property Project $Project
 * 
 * @method double       getValue()        Returns the current record's "value" value
 * @method integer      getTypeId()       Returns the current record's "type_id" value
 * @method integer      getProjectId()    Returns the current record's "project_id" value
 * @method integer      getUserId()       Returns the current record's "user_id" value
 * @method TimeItemType getTimeItemType() Returns the current record's "TimeItemType" value
 * @method User         getUser()         Returns the current record's "User" value
 * @method Project      getProject()      Returns the current record's "Project" value
 * @method TimeLogItem  setValue()        Sets the current record's "value" value
 * @method TimeLogItem  setTypeId()       Sets the current record's "type_id" value
 * @method TimeLogItem  setProjectId()    Sets the current record's "project_id" value
 * @method TimeLogItem  setUserId()       Sets the current record's "user_id" value
 * @method TimeLogItem  setTimeItemType() Sets the current record's "TimeItemType" value
 * @method TimeLogItem  setUser()         Sets the current record's "User" value
 * @method TimeLogItem  setProject()      Sets the current record's "Project" value
 * 
 * @package    timeboxx
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTimeLogItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_timelog_item');
        $this->hasColumn('value', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('type_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('project_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TimeItemType', array(
             'local' => 'type_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}