<?php

/**
 * BaseAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $type
 * @property date $valid_until
 * @property string $name
 * @property Doctrine_Collection $users
 * @property Doctrine_Collection $TimeItemTypes
 * @property Doctrine_Collection $Projects
 * 
 * @method enum                getType()          Returns the current record's "type" value
 * @method date                getValidUntil()    Returns the current record's "valid_until" value
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getUsers()         Returns the current record's "users" collection
 * @method Doctrine_Collection getTimeItemTypes() Returns the current record's "TimeItemTypes" collection
 * @method Doctrine_Collection getProjects()      Returns the current record's "Projects" collection
 * @method Account             setType()          Sets the current record's "type" value
 * @method Account             setValidUntil()    Sets the current record's "valid_until" value
 * @method Account             setName()          Sets the current record's "name" value
 * @method Account             setUsers()         Sets the current record's "users" collection
 * @method Account             setTimeItemTypes() Sets the current record's "TimeItemTypes" collection
 * @method Account             setProjects()      Sets the current record's "Projects" collection
 * 
 * @package    timeboxx
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_account');
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'free',
              1 => 'small',
              2 => 'pro',
              3 => 'unlimited',
             ),
             ));
        $this->hasColumn('valid_until', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User as users', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $this->hasMany('TimeItemType as TimeItemTypes', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $this->hasMany('Project as Projects', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}