<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property integer $account_id
 * @property Account $Account
 * @property Doctrine_Collection $TimeLogItems
 * @property Doctrine_Collection $OwnedProjects
 * @property Doctrine_Collection $Project
 * @property Doctrine_Collection $Setting
 * 
 * @method string              getFirstName()     Returns the current record's "first_name" value
 * @method string              getLastName()      Returns the current record's "last_name" value
 * @method string              getEmail()         Returns the current record's "email" value
 * @method integer             getAccountId()     Returns the current record's "account_id" value
 * @method Account             getAccount()       Returns the current record's "Account" value
 * @method Doctrine_Collection getTimeLogItems()  Returns the current record's "TimeLogItems" collection
 * @method Doctrine_Collection getOwnedProjects() Returns the current record's "OwnedProjects" collection
 * @method Doctrine_Collection getProject()       Returns the current record's "Project" collection
 * @method Doctrine_Collection getSetting()       Returns the current record's "Setting" collection
 * @method User                setFirstName()     Sets the current record's "first_name" value
 * @method User                setLastName()      Sets the current record's "last_name" value
 * @method User                setEmail()         Sets the current record's "email" value
 * @method User                setAccountId()     Sets the current record's "account_id" value
 * @method User                setAccount()       Sets the current record's "Account" value
 * @method User                setTimeLogItems()  Sets the current record's "TimeLogItems" collection
 * @method User                setOwnedProjects() Sets the current record's "OwnedProjects" collection
 * @method User                setProject()       Sets the current record's "Project" collection
 * @method User                setSetting()       Sets the current record's "Setting" collection
 * 
 * @package    timeboxx
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_user');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('account_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id'));

        $this->hasMany('TimeLogItem as TimeLogItems', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Project as OwnedProjects', array(
             'local' => 'id',
             'foreign' => 'owner_id'));

        $this->hasMany('Project', array(
             'refClass' => 'ProjectUser',
             'local' => 'user_id',
             'foreign' => 'project_id'));

        $this->hasMany('Setting', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}