<?php

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $number
 * @property integer $owner_id
 * @property User $Owner
 * @property Doctrine_Collection $AssignedUser
 * @property Doctrine_Collection $TimeLogItems
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getNumber()       Returns the current record's "number" value
 * @method integer             getOwnerId()      Returns the current record's "owner_id" value
 * @method User                getOwner()        Returns the current record's "Owner" value
 * @method Doctrine_Collection getAssignedUser() Returns the current record's "AssignedUser" collection
 * @method Doctrine_Collection getTimeLogItems() Returns the current record's "TimeLogItems" collection
 * @method Project             setName()         Sets the current record's "name" value
 * @method Project             setNumber()       Sets the current record's "number" value
 * @method Project             setOwnerId()      Sets the current record's "owner_id" value
 * @method Project             setOwner()        Sets the current record's "Owner" value
 * @method Project             setAssignedUser() Sets the current record's "AssignedUser" collection
 * @method Project             setTimeLogItems() Sets the current record's "TimeLogItems" collection
 * 
 * @package    timeboxx
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_project');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('number', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('owner_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User as Owner', array(
             'local' => 'owner_id',
             'foreign' => 'id'));

        $this->hasMany('User as AssignedUser', array(
             'refClass' => 'ProjectUser',
             'local' => 'project_id',
             'foreign' => 'user_id'));

        $this->hasMany('TimeLogItem as TimeLogItems', array(
             'local' => 'id',
             'foreign' => 'project_id'));
    }
}