<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/08/05 20:59:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=timeboxx',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
