<?php

/**
 * Credential
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * * @package    sutimeboxx
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Credential extends BaseCredential
{
    const TIMETRACKING_EDIT = 'credential.timetracking.edit';
}