<?php

/**
 * CredentialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CredentialTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object CredentialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Credential');
    }

    public static function getGroupedCredentials()
    {
        $credentials = Doctrine::getTable('Credential')->findAll();

        $result = array();

        // create grouped array
        foreach ($credentials as $credential) {
            if (!array_key_exists($credential->group_name, $result)) {
                $result[$credential->group_name] = array();
            }

            $result[$credential->group_name][] = $credential;
        }

        return $result;
    }

}