<?php

/**
 * RoleCredentialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleCredentialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoleCredentialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoleCredential');
    }
}