<?php

/**
 * RoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object RoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Role');
    }

    public function findByAccountId($account_id)
    {
        return Doctrine_Query::create()
                    ->from('Role r')
                    ->where('r.account_id=? AND r.deleted_at IS NULL',
                                array($account_id))
                    ->orderBy('r.name ASC')
                    ->execute();
    }

}