<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/08/17 10:25:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=timeboxx_ng',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
