<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtbaccount extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('tb_account', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'free',
              1 => 'small',
              2 => 'pro',
              3 => 'unlimited',
              ),
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('tb_account');
    }
}