<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtbuser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('tb_user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'account_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('tb_user');
    }
}