<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtbtimelogitem extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('tb_timelog_item', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'value' => 
             array(
              'type' => 'double',
              'length' => NULL,
             ),
             'type_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'project_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('tb_timelog_item');
    }
}