<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('tb_settings', 'locked');
        $this->addColumn('tb_settings', 'theme', 'string', '255', array(
             'default' => 'default',
             ));
    }

    public function down()
    {
        $this->addColumn('tb_settings', 'locked', 'boolean', '25', array(
             ));
        $this->removeColumn('tb_settings', 'theme');
    }
}