<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tb_account', 'valid_until', 'date', '25', array(
             ));
        $this->addColumn('tb_account', 'name', 'string', '100', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tb_account', 'valid_until');
        $this->removeColumn('tb_account', 'name');
    }
}