<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tb_token', 'tb_token_user_id_tb_user_id', array(
             'name' => 'tb_token_user_id_tb_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'tb_user',
             ));
        $this->addIndex('tb_token', 'tb_token_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tb_token', 'tb_token_user_id_tb_user_id');
        $this->removeIndex('tb_token', 'tb_token_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}