<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tb_settings', 'culture', 'string', '10', array(
             ));
        $this->addColumn('tb_settings', 'reminder', 'boolean', '25', array(
             ));
        $this->addColumn('tb_settings', 'locked', 'boolean', '25', array(
             ));
        $this->addColumn('tb_user', 'username', 'string', '255', array(
             ));
        $this->addColumn('tb_user', 'password', 'string', '255', array(
             ));
        $this->addColumn('tb_user', 'administrator', 'boolean', '25', array(
             ));
        $this->addColumn('tb_user', 'locked', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tb_settings', 'culture');
        $this->removeColumn('tb_settings', 'reminder');
        $this->removeColumn('tb_settings', 'locked');
        $this->removeColumn('tb_user', 'username');
        $this->removeColumn('tb_user', 'password');
        $this->removeColumn('tb_user', 'administrator');
        $this->removeColumn('tb_user', 'locked');
    }
}