<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tb_missing_time_entries', 'tb_missing_time_entries_user_id_tb_user_id', array(
             'name' => 'tb_missing_time_entries_user_id_tb_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'tb_user',
             ));
        $this->createForeignKey('tb_project', 'tb_project_account_id_tb_account_id', array(
             'name' => 'tb_project_account_id_tb_account_id',
             'local' => 'account_id',
             'foreign' => 'id',
             'foreignTable' => 'tb_account',
             ));
        $this->addIndex('tb_missing_time_entries', 'tb_missing_time_entries_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('tb_project', 'tb_project_account_id', array(
             'fields' => 
             array(
              0 => 'account_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tb_missing_time_entries', 'tb_missing_time_entries_user_id_tb_user_id');
        $this->dropForeignKey('tb_project', 'tb_project_account_id_tb_account_id');
        $this->removeIndex('tb_missing_time_entries', 'tb_missing_time_entries_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('tb_project', 'tb_project_account_id', array(
             'fields' => 
             array(
              0 => 'account_id',
             ),
             ));
    }
}