<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tb_timelog_item', 'note', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tb_timelog_item', 'note');
    }
}