<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tb_timeitem_type', 'deleted_at', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tb_timeitem_type', 'deleted_at');
    }
}