<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ts_role_credential', 'ts_role_credential_credential_id_ts_credential_id', array(
             'name' => 'ts_role_credential_credential_id_ts_credential_id',
             'local' => 'credential_id',
             'foreign' => 'id',
             'foreignTable' => 'ts_credential',
             ));
        $this->createForeignKey('ts_role_credential', 'ts_role_credential_role_id_tb_role_id', array(
             'name' => 'ts_role_credential_role_id_tb_role_id',
             'local' => 'role_id',
             'foreign' => 'id',
             'foreignTable' => 'tb_role',
             ));
        $this->addIndex('ts_role_credential', 'ts_role_credential_credential_id', array(
             'fields' => 
             array(
              0 => 'credential_id',
             ),
             ));
        $this->addIndex('ts_role_credential', 'ts_role_credential_role_id', array(
             'fields' => 
             array(
              0 => 'role_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ts_role_credential', 'ts_role_credential_credential_id_ts_credential_id');
        $this->dropForeignKey('ts_role_credential', 'ts_role_credential_role_id_tb_role_id');
        $this->removeIndex('ts_role_credential', 'ts_role_credential_credential_id', array(
             'fields' => 
             array(
              0 => 'credential_id',
             ),
             ));
        $this->removeIndex('ts_role_credential', 'ts_role_credential_role_id', array(
             'fields' => 
             array(
              0 => 'role_id',
             ),
             ));
    }
}