<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ts_credential', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'group_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('ts_role_credential', array(
             'role_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '11',
             ),
             'credential_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '11',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'role_id',
              1 => 'credential_id',
             ),
             ));
        $this->removeColumn('tb_role', 'operations');
    }

    public function down()
    {
        $this->dropTable('ts_credential');
        $this->dropTable('ts_role_credential');
        $this->addColumn('tb_role', 'operations', 'integer', '20', array(
             ));
    }
}