<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tb_role', 'tb_role_account_id_tb_account_id', array(
             'name' => 'tb_role_account_id_tb_account_id',
             'local' => 'account_id',
             'foreign' => 'id',
             'foreignTable' => 'tb_account',
             ));
        $this->addIndex('tb_role', 'tb_role_account_id', array(
             'fields' => 
             array(
              0 => 'account_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tb_role', 'tb_role_account_id_tb_account_id');
        $this->removeIndex('tb_role', 'tb_role_account_id', array(
             'fields' => 
             array(
              0 => 'account_id',
             ),
             ));
    }
}