<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version31 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tb_project_user', 'role_id', 'integer', '20', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tb_project_user', 'role_id');
    }
}