<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tb_account', 'workingdays', 'integer', '20', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tb_account', 'workingdays');
    }
}