<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version32 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tb_project_user', 'tb_project_user_role_id_tb_role_id', array(
             'name' => 'tb_project_user_role_id_tb_role_id',
             'local' => 'role_id',
             'foreign' => 'id',
             'foreignTable' => 'tb_role',
             ));
        $this->addIndex('tb_project_user', 'tb_project_user_role_id', array(
             'fields' => 
             array(
              0 => 'role_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tb_project_user', 'tb_project_user_role_id_tb_role_id');
        $this->removeIndex('tb_project_user', 'tb_project_user_role_id', array(
             'fields' => 
             array(
              0 => 'role_id',
             ),
             ));
    }
}