<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version35 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tb_account', 'max_hours_per_day', 'double', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('tb_account', 'max_hours_per_day');
    }
}