<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/11/30 10:20:12
sfConfig::add(array(
  'app_version' => '0.1.0',
  'app_autologin_expiration' => 84600,
  'app_notification_missing_bookings' => true,
  'app_user_cultures' => array (
  0 => 'de',
  1 => 'en',
),
));
