<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/12/15 14:37:30
sfConfig::add(array(
  'app_version' => '0.6.0',
  'app_autologin_expiration' => 84600,
  'app_notification_missing_bookings' => true,
  'app_user_cultures' => array (
  0 => 'de',
  1 => 'en',
),
  'app_system_email' => array (
  'host' => 'servicemail.rotex.de',
  'authentification' => true,
  'port' => 25,
  'username' => NULL,
  'password' => NULL,
  'from' => 'timo.haberkern@rotex.de',
),
));
