<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/12/03 10:19:36
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
);
