<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/11/30 10:31:12
sfConfig::add(array(
  'mod_admintimeitemtype_enabled' => true,
  'mod_admintimeitemtype_view_class' => 'sfPHP',
));
