<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/12/06 11:36:57
$this->security = array (
  'sendpassword' => 
  array (
    'is_secure' => false,
  ),
  'newpassword' => 
  array (
    'is_secure' => false,
  ),
  'createpassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
