<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/12/06 11:51:01
sfConfig::add(array(
  'mod_admintimeitemtype_enabled' => true,
  'mod_admintimeitemtype_view_class' => 'sfPHP',
));
